<?php return array (
  'flosch\\slideshow\\Plugin' => 'plugins\\flosch\\slideshow\\Plugin.php',
  'october\\demo\\Plugin' => 'plugins\\october\\demo\\Plugin.php',
  'rainlab\\blog\\Plugin' => 'plugins\\rainlab\\blog\\Plugin.php',
  'rainlab\\forum\\Plugin' => 'plugins\\rainlab\\forum\\Plugin.php',
  'rainlab\\pages\\Plugin' => 'plugins\\rainlab\\pages\\Plugin.php',
  'rainlab\\user\\Plugin' => 'plugins\\rainlab\\user\\Plugin.php',
  'RainLab\\Blog\\Classes\\TagProcessor' => 'plugins\\rainlab\\blog\\classes\\TagProcessor.php',
  'RainLab\\User\\Models\\User' => 'plugins\\rainlab\\user\\models\\User.php',
  'RainLab\\User\\Controllers\\Users' => 'plugins\\rainlab\\user\\controllers\\Users.php',
  'RainLab\\Pages\\Classes\\Controller' => 'plugins\\rainlab\\pages\\classes\\Controller.php',
  'RainLab\\Pages\\Classes\\Router' => 'plugins\\rainlab\\pages\\classes\\Router.php',
  'RainLab\\Pages\\Classes\\PageList' => 'plugins\\rainlab\\pages\\classes\\PageList.php',
  'RainLab\\Pages\\Classes\\Page' => 'plugins\\rainlab\\pages\\classes\\Page.php',
);